version: "2.0"
services:
  apache:
    image: fhck-server:0.1
    container_name: fhck-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - wordpress
    depends_on:
      - wordpress
    volumes:
      - ./:/var/www/html/

  fix-mariadb-permissions:
    image: "bitnami/mariadb:10.1-master"
    user: root
    command: chown -R 1001:1001 /bitnami/mariadb
    volumes:
      - ./mariadb/data:/bitnami/mariadb

  wordpress:
    container_name: fhck-database
    image: "bitnami/mariadb:10.1-master"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=fhck
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/bitnami/mariadb
    depends_on:
      - fix-mariadb-permissions
